#!/bin/bash
# Oil & Gas Document Translator - Unix/Linux/macOS Setup Script
# Run: chmod +x scripts/setup.sh && ./scripts/setup.sh

set -e

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║     🛢️  Oil & Gas Document Translator - Setup Wizard 🛢️      ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Mode selection
MODE=""
if [ -z "$1" ]; then
    echo -e "${YELLOW}Select your translation mode:${NC}"
    echo ""
    echo -e "  ${GREEN}[1] SELF-HOSTED (Free - \$0)${NC}"
    echo "      - Uses NLLB + PaddleOCR (runs on CPU)"
    echo "      - Slower but completely free"
    echo "      - Requires 16GB+ RAM, ~20GB disk space"
    echo ""
    echo -e "  ${BLUE}[2] BUDGET (~\$3 per document)${NC}"
    echo "      - Uses DeepSeek API + PaddleOCR"
    echo "      - Good balance of speed and cost"
    echo "      - Requires DeepSeek API key (5M free tokens!)"
    echo ""
    echo -e "  ${MAGENTA}[3] PREMIUM (Best Quality)${NC}"
    echo "      - Uses Claude + Azure Document Intelligence"
    echo "      - Highest accuracy (97%+)"
    echo "      - Requires Azure + Anthropic API keys"
    echo ""
    
    read -p "Enter your choice (1-3): " choice
    
    case $choice in
        1) MODE="self_hosted" ;;
        2) MODE="budget" ;;
        3) MODE="premium" ;;
        *)
            echo -e "${YELLOW}Invalid choice. Defaulting to self_hosted.${NC}"
            MODE="self_hosted"
            ;;
    esac
else
    MODE=$1
fi

echo ""
echo -e "${GREEN}Selected mode: $MODE${NC}"
echo ""

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Check Python
echo -e "${YELLOW}Checking Python installation...${NC}"
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}ERROR: Python 3 not found. Please install Python 3.11+.${NC}"
    exit 1
fi

PYTHON_VERSION=$(python3 --version)
echo -e "${GREEN}Found: $PYTHON_VERSION${NC}"

# Check Node.js
echo -e "${YELLOW}Checking Node.js installation...${NC}"
if ! command -v node &> /dev/null; then
    echo -e "${RED}ERROR: Node.js not found. Please install Node.js 18+.${NC}"
    exit 1
fi

NODE_VERSION=$(node --version)
echo -e "${GREEN}Found: Node.js $NODE_VERSION${NC}"

# Setup backend
echo ""
echo -e "${YELLOW}Setting up Python virtual environment...${NC}"
cd "$PROJECT_DIR/backend"

if [ ! -d "venv" ]; then
    python3 -m venv venv
fi

# Activate and install dependencies
echo -e "${YELLOW}Installing Python dependencies (this may take a while)...${NC}"
source venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt

# Create .env file
echo ""
echo -e "${YELLOW}Creating configuration file...${NC}"

cat > .env << EOF
# Oil & Gas Document Translator Configuration
# Generated by setup script

TRANSLATION_MODE=$MODE
DEBUG=false
HOST=0.0.0.0
PORT=8000
CORS_ORIGINS=["http://localhost:3000", "http://127.0.0.1:3000"]

# File handling
MAX_FILE_SIZE_MB=600
UPLOAD_DIR=./uploads
OUTPUT_DIR=./outputs
TEMP_DIR=./temp

# Database
DATABASE_URL=sqlite+aiosqlite:///./translator.db
EOF

if [ "$MODE" = "budget" ] || [ "$MODE" = "premium" ]; then
    cat >> .env << EOF

# DeepSeek API (Budget mode)
# Get your free API key at: https://platform.deepseek.com
DEEPSEEK_API_KEY=
DEEPSEEK_BASE_URL=https://api.deepseek.com/v1
DEEPSEEK_MODEL=deepseek-chat
EOF
fi

if [ "$MODE" = "premium" ]; then
    cat >> .env << EOF

# Azure Document Intelligence (Premium OCR)
# https://azure.microsoft.com/en-us/products/ai-services/document-intelligence
AZURE_DOC_ENDPOINT=
AZURE_DOC_KEY=

# Anthropic Claude (Premium Translation)
# https://console.anthropic.com
ANTHROPIC_API_KEY=
CLAUDE_MODEL=claude-3-5-sonnet-20241022
EOF
fi

# Create directories
mkdir -p uploads outputs temp

# Setup frontend
echo ""
echo -e "${YELLOW}Setting up frontend...${NC}"
cd "$PROJECT_DIR/frontend"
npm install

# Create frontend .env
echo "NEXT_PUBLIC_API_URL=http://localhost:8000" > .env.local

echo ""
echo -e "${GREEN}╔═══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                    ✅ Setup Complete!                         ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════════════╝${NC}"
echo ""

if [ "$MODE" = "budget" ]; then
    echo -e "${YELLOW}⚠️  IMPORTANT: Add your DeepSeek API key to backend/.env${NC}"
    echo "   Get free 5M tokens at: https://platform.deepseek.com"
    echo ""
fi

if [ "$MODE" = "premium" ]; then
    echo -e "${YELLOW}⚠️  IMPORTANT: Add your API keys to backend/.env${NC}"
    echo "   - Azure Document Intelligence: https://azure.microsoft.com"
    echo "   - Anthropic Claude: https://console.anthropic.com"
    echo ""
fi

echo -e "${CYAN}To start the application:${NC}"
echo ""
echo "  1. Start the backend:"
echo "     cd backend"
echo "     source venv/bin/activate"
echo "     uvicorn app.main:app --reload"
echo ""
echo "  2. Start the frontend (new terminal):"
echo "     cd frontend"
echo "     npm run dev"
echo ""
echo "  3. Open http://localhost:3000 in your browser"
echo ""

cd "$PROJECT_DIR"

