# Oil & Gas Document Translator - Windows Setup Script
# Run: powershell -ExecutionPolicy Bypass -File scripts/setup.ps1

param(
    [ValidateSet("self_hosted", "budget", "premium")]
    [string]$Mode = ""
)

Write-Host @"

 ╔═══════════════════════════════════════════════════════════════╗
 ║     🛢️  Oil & Gas Document Translator - Setup Wizard 🛢️      ║
 ╚═══════════════════════════════════════════════════════════════╝

"@ -ForegroundColor Cyan

# Mode selection
if (-not $Mode) {
    Write-Host "Select your translation mode:" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "  [1] SELF-HOSTED (Free - `$0)" -ForegroundColor Green
    Write-Host "      - Uses NLLB + PaddleOCR (runs on CPU)"
    Write-Host "      - Slower but completely free"
    Write-Host "      - Requires 16GB+ RAM, ~20GB disk space"
    Write-Host ""
    Write-Host "  [2] BUDGET (~`$3 per document)" -ForegroundColor Blue
    Write-Host "      - Uses DeepSeek API + PaddleOCR"
    Write-Host "      - Good balance of speed and cost"
    Write-Host "      - Requires DeepSeek API key (5M free tokens!)"
    Write-Host ""
    Write-Host "  [3] PREMIUM (Best Quality)" -ForegroundColor Magenta
    Write-Host "      - Uses Claude + Azure Document Intelligence"
    Write-Host "      - Highest accuracy (97%+)"
    Write-Host "      - Requires Azure + Anthropic API keys"
    Write-Host ""

    $choice = Read-Host "Enter your choice (1-3)"
    
    switch ($choice) {
        "1" { $Mode = "self_hosted" }
        "2" { $Mode = "budget" }
        "3" { $Mode = "premium" }
        default {
            Write-Host "Invalid choice. Defaulting to self_hosted." -ForegroundColor Yellow
            $Mode = "self_hosted"
        }
    }
}

Write-Host ""
Write-Host "Selected mode: $Mode" -ForegroundColor Green
Write-Host ""

# Check Python
Write-Host "Checking Python installation..." -ForegroundColor Yellow
$python = Get-Command python -ErrorAction SilentlyContinue
if (-not $python) {
    Write-Host "ERROR: Python not found. Please install Python 3.11+." -ForegroundColor Red
    Write-Host "Download from: https://www.python.org/downloads/" -ForegroundColor Yellow
    exit 1
}

$pythonVersion = python --version
Write-Host "Found: $pythonVersion" -ForegroundColor Green

# Check Node.js
Write-Host "Checking Node.js installation..." -ForegroundColor Yellow
$node = Get-Command node -ErrorAction SilentlyContinue
if (-not $node) {
    Write-Host "ERROR: Node.js not found. Please install Node.js 18+." -ForegroundColor Red
    Write-Host "Download from: https://nodejs.org/" -ForegroundColor Yellow
    exit 1
}

$nodeVersion = node --version
Write-Host "Found: Node.js $nodeVersion" -ForegroundColor Green

# Create virtual environment
Write-Host ""
Write-Host "Setting up Python virtual environment..." -ForegroundColor Yellow
Set-Location -Path "$PSScriptRoot\..\backend"

if (-not (Test-Path "venv")) {
    python -m venv venv
}

# Activate and install dependencies
Write-Host "Installing Python dependencies (this may take a while)..." -ForegroundColor Yellow
.\venv\Scripts\Activate.ps1
pip install --upgrade pip
pip install -r requirements.txt

# Create .env file
Write-Host ""
Write-Host "Creating configuration file..." -ForegroundColor Yellow

$envContent = @"
# Oil & Gas Document Translator Configuration
# Generated by setup script

TRANSLATION_MODE=$Mode
DEBUG=false
HOST=0.0.0.0
PORT=8000
CORS_ORIGINS=["http://localhost:3000", "http://127.0.0.1:3000"]

# File handling
MAX_FILE_SIZE_MB=600
UPLOAD_DIR=./uploads
OUTPUT_DIR=./outputs
TEMP_DIR=./temp

# Database
DATABASE_URL=sqlite+aiosqlite:///./translator.db
"@

if ($Mode -eq "budget" -or $Mode -eq "premium") {
    $envContent += @"

# DeepSeek API (Budget mode)
# Get your free API key at: https://platform.deepseek.com
DEEPSEEK_API_KEY=
DEEPSEEK_BASE_URL=https://api.deepseek.com/v1
DEEPSEEK_MODEL=deepseek-chat
"@
}

if ($Mode -eq "premium") {
    $envContent += @"

# Azure Document Intelligence (Premium OCR)
# https://azure.microsoft.com/en-us/products/ai-services/document-intelligence
AZURE_DOC_ENDPOINT=
AZURE_DOC_KEY=

# Anthropic Claude (Premium Translation)
# https://console.anthropic.com
ANTHROPIC_API_KEY=
CLAUDE_MODEL=claude-3-5-sonnet-20241022
"@
}

Set-Content -Path ".env" -Value $envContent

# Create directories
New-Item -ItemType Directory -Force -Path uploads | Out-Null
New-Item -ItemType Directory -Force -Path outputs | Out-Null
New-Item -ItemType Directory -Force -Path temp | Out-Null

# Setup frontend
Write-Host ""
Write-Host "Setting up frontend..." -ForegroundColor Yellow
Set-Location -Path "$PSScriptRoot\..\frontend"
npm install

# Create frontend .env
$frontendEnv = "NEXT_PUBLIC_API_URL=http://localhost:8000"
Set-Content -Path ".env.local" -Value $frontendEnv

Write-Host ""
Write-Host @"
╔═══════════════════════════════════════════════════════════════╗
║                    ✅ Setup Complete!                         ║
╚═══════════════════════════════════════════════════════════════╝
"@ -ForegroundColor Green

if ($Mode -eq "budget") {
    Write-Host @"
⚠️  IMPORTANT: Add your DeepSeek API key to backend/.env
   Get free 5M tokens at: https://platform.deepseek.com

"@ -ForegroundColor Yellow
}

if ($Mode -eq "premium") {
    Write-Host @"
⚠️  IMPORTANT: Add your API keys to backend/.env
   - Azure Document Intelligence: https://azure.microsoft.com
   - Anthropic Claude: https://console.anthropic.com

"@ -ForegroundColor Yellow
}

Write-Host @"
To start the application:

  1. Start the backend:
     cd backend
     .\venv\Scripts\Activate.ps1
     uvicorn app.main:app --reload

  2. Start the frontend (new terminal):
     cd frontend
     npm run dev

  3. Open http://localhost:3000 in your browser

"@ -ForegroundColor Cyan

Set-Location -Path $PSScriptRoot\..

